name: homeprojectpageflutter
description: Thailand_RIS-IGEM-Wiki
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.8
  flutter_web_plugins:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: druk
      fonts:
        - asset: assets/fonts/druk.ttf
          style: normal
    - family: rockabye
      fonts:
        - asset: assets/fonts/rockabye.ttf
          style: normal
